import { MigrationInterface, QueryRunner } from "typeorm";

export class AddUserEntity1716827409694 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "user" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "email" varchar(255) UNIQUE NOT NULL, "hashedPassword" varchar(255) NOT NULL)`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
    }

}
