GET http://localhost:3000/

###

GET http://localhost:3000/ads

###

GET http://localhost:3000/ads?category=voiture

###

GET http://localhost:3000/ads?tags=jeans

###

GET http://localhost:3000/ads?tags=fashion&category=vêtement

###

POST http://localhost:3000/ads
Content-Type: application/json

  {
    "title": "Car to sell",
    "description":
      "My car is blue, working fine. I'm selling it because I've got a new one",
    "owner": "car.seller@gmail.com",
    "price": 10000,
    "picture": "https://www.automobile-magazine.fr/asset/cms/34973/config/28294/apres-plusieurs-prototypes-la-bollore-bluecar-a-fini-par-devoiler-sa-version-definitive.jpg",
    "location": "Paris",
    "createdAt": "2023-10-05",
    "category": "vêtement",
    "tags": ["jeans", "fashion"]
  }

###

DELETE http://localhost:3000/ads/5

###

PUT http://localhost:3000/ads/2
Content-Type: application/json

{
  "title": "Snowboard to sell",
  "description":
    "My car is blue, working fine. I'm selling it because I've got a new one",
  "owner": "car.seller@gmail.com",
  "price": 30000,
  "picture": "https://images.lecho.be/view?iid=dc:113129565&context=ONLINE&ratio=16/9&width=640&u=1508242455000",
  "location": "Paris",
  "createdAt": "2023-10-05T10:14:15.922Z",
  "category": "voiture",
  "tags": ["toto", "wheel"]
}

###

GET http://localhost:3000/categories

###

GET http://localhost:3000/categories?name=v

###

GET http://localhost:3000/tags?name=whe

###

DELETE http://localhost:3000/tags/11